version: '3.5'

services:
    frontend:
      container_name: frontend  # Container name
      build:
        context: frontend
        dockerfile: Dockerfile
      volumes:
        - './frontend:/usr/src/app'
      ports:
        - '4200:4200'
      environment:
        - API_URL=${API_URL}
      command: >
        bash -c "ng serve --host 0.0.0.0 --port 4200 --disable-host-check"
      links:
        - backend:backend
      networks:
        - php-project
    backend:
      container_name: backend
      build:
        args:
          user: admin
          uid: 1000
        context: backend
        dockerfile: Dockerfile
      restart: always
      env_file: .env
      command: php artisan serve --host 0.0.0.0
      environment:
        - "PHP_DB_USER=${PHP_DB_USER}"
        - "PHP_DB_PASSWORD=${PHP_DB_PASSWORD}"
        - "PHP_DB_DATABASE=php_project"
      volumes:
        - ./backend:/backend
      ports:
        - '8000:8000'
      links:
        - database:database
      depends_on:
        - database
      networks:
        - php-project
    database:
      container_name: database
      restart: always
      env_file: .env
      environment:
        - "PHP_DB_USER=${PHP_DB_USER}"
        - "PHP_DB_PASSWORD=${PHP_DB_PASSWORD}"
        - "PHP_DB_DATABASE=php_project"
      build: './db'
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      networks:
        - php-project

networks:
  php-project:
    name: php-project-network
